# This is a basic workflow to help you get started with Actions

name: Build&Push image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python:
    runs-on: lxc
    steps:
      - uses: actions/checkout@v4
      - uses: redhat-actions/buildah-build@v2
        with:
          context: python
          containerfiles: python/Dockerfile
          tags: ghcr.io/${{ github.repository }}:py-c

  other:
    needs: python
    runs-on: lxc
    strategy:
      matrix:
        tag: [cpp, novnc, sql, pyai]
    steps:
      - uses: actions/checkout@v4
      - uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ matrix.tag }}
          containerfiles: ${{ matrix.tag }}/Dockerfile
          tags: ghcr.io/${{ github.repository }}:${{ matrix.tag }}

  push:
    needs: other
    runs-on: lxc
    permissions:
      packages: write
    strategy:
      matrix:
        tag: [py-c, cpp, novnc, sql, pyai]
    steps:
      - name: Login to GitHub Container Registry
        run: podman login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - uses: redhat-actions/push-to-registry@v2
        with:
          tags: ghcr.io/${{ github.repository }}:${{ matrix.tag }}
  
  cleanup:
    needs: push
    runs-on: lxc
    permissions:
      packages: write
    steps:
      - uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: cleanup
        run: podman images | grep ghcr.io/${{ github.repository }} | awk '{ print $3 }' | xargs -r podman rmi -f