# This is a basic workflow to help you get started with Actions

name: Build&Push image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python:
    runs-on: arc
    container:
      image: ghcr.nju.edu.cn/kaniko-build/dist/chainguard-dev-kaniko/executor:v1.25.1-debug
    steps:
      - &checkout
        run: |
          wget https://github.com/eoeair/jupyter/archive/refs/heads/main.zip
          unzip main.zip
          mv jupyter-main/* .
          rm -rf jupyter-main main.zip
      - &login
        run: |
          mkdir -p /kaniko/.docker
          cat > /kaniko/.docker/config.json <<EOF
          {
            "auths": {
              "ghcr.io": {
                "auth": "$(echo -n '${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}' | base64)"
              }
            }
          }
          EOF
      - run: |
          /kaniko/executor \
            --context python \
            --dockerfile python/Dockerfile \
            --destination ghcr.io/${{ github.repository }}:python \
            --single-snapshot
  other:
    needs: python
    runs-on: arc
    container:
      image: ghcr.nju.edu.cn/kaniko-build/dist/chainguard-dev-kaniko/executor:v1.25.1-debug
    strategy:
      matrix:
        tag: [cpp, novnc, sql, pyai]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context ${{ matrix.tag }} \
            --dockerfile ${{ matrix.tag }}/Dockerfile \
            --destination ghcr.io/${{ github.repository }}:${{ matrix.tag }} \
            --single-snapshot

  cleanup:
    needs: [other]
    runs-on: arc
    container:
      image: ghcr.nju.edu.cn/eoeair/cenv:base
    steps:
      - uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}